# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subsidence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10subsidence.proto\"J\n\x15SubsidencePointStream\x12\x0f\n\x03lng\x18\x01 \x03(\x01\x42\x02\x10\x01\x12\x0f\n\x03lat\x18\x02 \x03(\x01\x42\x02\x10\x01\x12\x0f\n\x03val\x18\x03 \x03(\x01\x42\x02\x10\x01\x42:\n)com.atomdata.zhongjian.dataplatform.protoB\x0bMessageInfoH\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subsidence_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.atomdata.zhongjian.dataplatform.protoB\013MessageInfoH\001'
  _SUBSIDENCEPOINTSTREAM.fields_by_name['lng']._options = None
  _SUBSIDENCEPOINTSTREAM.fields_by_name['lng']._serialized_options = b'\020\001'
  _SUBSIDENCEPOINTSTREAM.fields_by_name['lat']._options = None
  _SUBSIDENCEPOINTSTREAM.fields_by_name['lat']._serialized_options = b'\020\001'
  _SUBSIDENCEPOINTSTREAM.fields_by_name['val']._options = None
  _SUBSIDENCEPOINTSTREAM.fields_by_name['val']._serialized_options = b'\020\001'
  _SUBSIDENCEPOINTSTREAM._serialized_start=20
  _SUBSIDENCEPOINTSTREAM._serialized_end=94
# @@protoc_insertion_point(module_scope)
